### ISSUE TITLE
Update to latest version of elm-community/elm-test

### ISSUE THREAD

**Issue by avh4** [ktonon/elm-test-extra#2]
The new `elm-test` command line runner requires elm-community/elm-test version 4.0.0+, so any project that wants to upgrade and uses elm-test-extra needs elm-test-extra to allow that version.

However, this is blocked on elm-test-bdd-style being upgraded first :)  https://github.com/rogeriochaves/elm-test-bdd-style/pull/7

I can make a PR for this after https://github.com/rogeriochaves/elm-test-bdd-style/pull/7 is merged and published.

**Comment by ktonon** [comment]
I removed the dependency on `elm-test-bdd-style`, [updated to elm-test 4](https://github.com/ktonon/elm-test-extra/commit/83cccf2eaf0c5aa6dc2df18b580d41518cd43efe), and published as `1.5.1`. Let me know if this fixes your problem and I'll close this issue.
